const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const test = require("node:test");

const root = path.join(__dirname, "..");
const html = fs.readFileSync(path.join(root, "web", "index.html"), "utf8");
const script = fs.readFileSync(path.join(root, "web", "app.js"), "utf8");
const css = fs.readFileSync(path.join(root, "web", "app.css"), "utf8");
const telemetry = fs.readFileSync(path.join(root, "race_engineer", "telemetry.py"), "utf8");
const electronMain = fs.readFileSync(path.join(root, "electron", "main.js"), "utf8");

test("test tab contains a live weather view using the official track layers", () => {
  assert.doesNotMatch(html, /id="awaiting-data"/);
  assert.match(html, /data-screen-panel="test"[\s\S]*class="test-weather-dashboard"/);
  assert.doesNotMatch(html, /class="test-weather-summary"/);
  assert.doesNotMatch(html, /id="test-weather-(?:date|time|type)"/);
  assert.match(html, /id="test-weather-map"[\s\S]*id="test-weather-map-layers"/);
  assert.match(html, /id="test-weather-map-content"/);
  assert.doesNotMatch(html, /test-weather-start-finish-sensor/);
  assert.match(css, /#test-weather-map circle\s*\{[\s\S]*?display: none !important;/);
  assert.match(html, /id="test-weather-track-outline" class="test-weather-track-outline"/);
  assert.match(html, /id="test-weather-cloud-layer"/);
  assert.match(html, /id="test-weather-zoom-toggle"[\s\S]*aria-pressed="false"/);
  assert.match(css, /\.test-weather-zoom-toggle\s*\{[\s\S]*?top:\s*14px;[\s\S]*?right:\s*14px;/);
  assert.doesNotMatch(html, /test-weather-panel-head/);
  assert.doesNotMatch(html, /id="test-weather-cloud-status"/);
  assert.doesNotMatch(html, /SDK values/);
  assert.match(html, /class="test-weather-compare"/);
  assert.match(html, /id="test-weather-radar-canvas"/);
  assert.doesNotMatch(html, /id="test-weather-radar-track-outline"/);
  assert.match(html, /id="test-weather-forecast" class="test-weather-forecast"/);
  assert.match(html, /class="test-weather-forecast-hour is-current"[\s\S]*12:05 am/);
  assert.match(css, /\.test-weather-forecast-track\s*\{[\s\S]*grid-template-columns: repeat\(9/);
  assert.match(css, /\.test-weather-layout\s*\{[\s\S]*grid-template-columns: minmax\(420px, 1fr\) minmax\(520px, 0\.8fr\)/);
  assert.match(css, /\.test-weather-map-card\s*\{[\s\S]*grid-template-rows: minmax\(0, 1fr\) auto/);
  assert.match(css, /\.test-weather-square\s*\{[\s\S]*aspect-ratio: auto/);
  assert.match(css, /\[data-screen-panel="test"\]\.is-visible\s*\{[\s\S]*?overflow: hidden/);
  assert.match(css, /\.test-weather-dashboard\s*\{[\s\S]*?height: 100%;[\s\S]*?min-height: 0/);
  assert.match(css, /\.test-weather-layout\s*\{[\s\S]*?height: auto;[\s\S]*?overflow: hidden/);
  assert.match(css, /\.test-weather-compare\s*\{[\s\S]*?height: 100%;[\s\S]*?overflow: hidden/);
  assert.match(css, /\.test-weather-map-card\s*\{[\s\S]*?height: 100%;[\s\S]*?min-height: 0/);
  assert.doesNotMatch(script, /testWeatherEstimateCardEl\?\.append\(testWeatherForecastEl\)/);
  assert.match(html, /id="test-weather-precipitation"/);
  assert.doesNotMatch(html, /test-weather-rain-overlay/);
  assert.match(html, /id="test-weather-radar-badge"[\s\S]*SIMULATED PRECIPITATION/);
  assert.doesNotMatch(html, />Current conditions<\/span>/);
  assert.doesNotMatch(html, /test-weather-data-note/);
  assert.match(html, /Cell positions are simulated; intensity and movement use live iRacing telemetry/);
  assert.match(script, /function syncTestWeatherMapLayers\(\)/);
  assert.match(script, /use\.setAttribute\("href", `#\$\{id\}`\)/);
});

test("weather view drives a clearly labelled simulated field from verified telemetry", () => {
  assert.match(telemetry, /_get_var\("Precipitation"\)/);
  assert.match(telemetry, /weekend_info\.get\("TrackWeatherType"\)/);
  assert.match(telemetry, /"precipitation": precipitation/);
  assert.match(script, /getRainPresentation\(weather\.precipitation\)/);
  assert.doesNotMatch(script, /formatWeatherType/);
  assert.match(script, /function getRainVisualState\(rainState, precipitation\)/);
  assert.match(script, /weather\.rain_state/);
  assert.match(script, /dataset\.rain = rain/);
  assert.match(script, /dataset\.cloudCover = cover \|\| "unknown"/);
  assert.match(css, /@keyframes weather-cloud-drift/);
  assert.match(css, /@keyframes weather-rain-fall/);
  assert.match(css, /data-rain="heavy"/);
  assert.match(script, /function drawSimulatedPrecipitationField\(/);
  assert.match(script, /function updateSimulatedPrecipitationField\(weather, hasRecentTelemetry\)/);
  assert.match(script, /testWeatherRadarState\.windDirection/);
  assert.match(script, /testWeatherRadarState\.windSpeed/);
  assert.match(script, /updateSimulatedPrecipitationField\(weather, hasRecentTelemetry\)/);
  assert.doesNotMatch(script, /WEATHER_RADAR_UPDATE_SECONDS/);
  assert.doesNotMatch(script, /lastWeatherRadarSignature/);
  assert.match(css, /\.test-weather-compare\s*\{[\s\S]*?grid-template-columns: minmax\(0, 1fr\)/);
  assert.doesNotMatch(electronMain, /desktopCapturer/);
  assert.doesNotMatch(electronMain, /thumbnail\.crop/);
  assert.match(script, /formatIngameTime\(telemetry\.session_time_of_day\)/);
  assert.doesNotMatch(html, /test-weather-map-footer/);
  assert.doesNotMatch(html, /test-weather-rain-scale/);
  assert.doesNotMatch(html, /test-weather-map-wind/);
  assert.doesNotMatch(html, /test-weather-map-reading/);
  assert.doesNotMatch(html, /test-weather-map-rain/);
  assert.doesNotMatch(html, /test-weather-compass/);
  assert.doesNotMatch(html, /test-weather-wind-arrow/);
  assert.match(script, /outlineEl\.setAttribute\("d", trackPathData\)/);
  assert.match(script, /contentEl\.setAttribute\("transform", `rotate\(90 /);
  assert.match(script, /const measurementEl = trackPathData \? outlineEl : layersEl/);
  assert.match(script, /const box = measurementEl\.getBBox\(\)/);
  assert.match(script, /const zoomScale = isTestWeatherZoomedOut \? 3 : 1/);
  assert.match(script, /setTestWeatherViewBox\(weatherMapEl, centerX, centerY, box\.height, box\.width, padding\)/);
  assert.match(script, /testWeatherZoomToggleEl\?\.addEventListener\("click"/);
  assert.match(script, /layersEl\.replaceChildren\(\);/);
});

test("live telemetry freshness uses receipt time and recovers from a silent stream", () => {
  assert.match(html, /<script src="\/app\.js\?v=[^"]+"><\/script>/);
  assert.match(script, /Date\.now\(\) - lastSnapshotAt <= freshnessLimitMs/);
  assert.doesNotMatch(script, /Date\.now\(\) - updatedAtMs <= freshnessLimitMs/);
  assert.match(script, /Date\.now\(\) - lastSnapshotAt > 1000[\s\S]*loadState\(\)/);
});
